# -*- coding: utf-8 -*-
#
# reportbuild documentation build configuration file, created by
# sphinx-quickstart on Sat Mar 12 16:51:41 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here
# (for info http://www.sphinx-doc.org/en/stable/config.html#confval-extensions):
# sys.path.insert(0, os.path.abspath("../../reportbuild/core"))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'gfzreport.sphinxbuild.core.extensions.setup',  # this is the custom one. MUST BE FIRST!
    'gfzreport.sphinxbuild.core.extensions.mapfigure',  # this is the custom one
    'gfzreport.sphinxbuild.core.extensions.gridfigure',  # this is the custom one
    'gfzreport.sphinxbuild.core.extensions.tabularrows',  # this is the custom one
    'gfzreport.sphinxbuild.core.extensions.includegraphics',  # this is the custom one
]


# ******************************************** WARNING
# THE VARIABLES BELOW SET THE MASTER DOCUMENT, AND THE RELATIVE LATEX FILES.
# AS THIS PROGRAM CAN COMPILE ONLY A SINGLE SOURCE (rst, md) FILE INTO A DEST FILE (html, latex, pdf),
# THE SETTINGS BELOW ARE SET IN ORDER TO ACHIEVE THAT
# CHANGING THESE ARGUMENTS IS STRONGLY DISCOURAGED
# *********************************************

# The document name of the “master” document, that is, the document that contains the root
# toctree directive. WE do NOT have a .. toctree:: in the master_doc THUS this is simply the ONLY
# source document to compile, which will be built with `master_doc` + `source_suffix` (se below)
# THIS ARGUMENT WILL BE READ IN ORDER TO GET THE OUTPUT FILE NAME (master_doc + '.html', master_doc + '.tex'
# etcetera)
# For info see:
# http://www.sphinx-doc.org/en/1.5.2/config.html#confval-master_doc (current as of July 2017), or
# http://www.sphinx-doc.org/en/latest/config.html#confval-master_doc
master_doc = 'tutorial'

# This is the suffix(es) of source filenames. You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
# BUT SPHINX DOES NOT TELL US WHAT HAPPENS IN CASE OF CONFLICTS, SO PROVIDE A SINGLE ELEMENT HERE:
source_suffix = '.rst'

# The argument below determines how to group the document tree into LaTeX source files.
# DO NOT CHANGE THIS ARGUMENT, IN PARTICULAR, DO NOT PROVIDE MORE THAN ONE ELEMENT
# For other latex related stuff, scroll below this config file
# For info see:
# http://www.sphinx-doc.org/en/1.5.2/config.html#confval-latex_documents (current as of July 2017), or
# http://www.sphinx-doc.org/en/latest/config.html#confval-latex_documents
latex_documents = [
    (master_doc, master_doc + '.tex', u'', u'', 'howto', False),
]

# ******************************************** END OF WARNING

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# enabble numfig (http://www.sphinx-doc.org/en/stable/config.html#confval-numfig):
numfig = True

# General information about the project. Obviously, Sphinx does not tell how and when they are
# rendered except and which consequences they have. Anyway, these variables are not used here.
project = u''
copyright = u''
author = u''

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'1.0'
# The full version, including alpha/beta/rc tags.
release = u'1.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# There are two options for replacing |today|: either, you set today to some non-false value,
# then it is used:
# today = ''

# Else, today_fmt is used as the format for a strftime call:
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files:
exclude_patterns = ['_*.rst', "*.log", 'Thumbs.db', '.DS_Store']

# The reST default role (used for this markup: `text`) to use for all documents:
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# Add any paths that contain templates here, relative to this directory.
templates_path = ['conf_files/html/templates']

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['conf_files/html/static_path']

# The name of an image file (relative to this directory) to place at the top
# of the sidebar. NOTE: AS LONG AS html_theme='alabaster',
# IT IS NOT CURRENTLY USED ANYWHERE BECAUSE WE SET embedded = True in
# layout.html (in templates dir), AS LONG AS OUR THEME IS alabaster!!
# For other themes, you should have a look at their path (see our layout.html). For instance haiku
# seems to ignore embedded
html_logo = "conf_files/html/GFZ-Logo_eng_RGB.png"

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes. NOTE: NOT ALL THEMES BEHAVE THE SAME. FOR INSTANCE, ALABASTER HAS
# A THEME WITH A JINJA VAR embedded WHICH, IF True (WE SET IT TO True IN OUR CUSTOM TEMPLATE)
# DOES NOT DISPLAY SIDEBARS AND OTHER STUFF. THUS, IF YOU CHANGE THIS YOU MIGHT ALSO NEED TO
# CHANGE layout.html in templates folder and style.css in static_path/css.
# SUGGESTION: DO NOT CHANGE THIS, RATHER only style.css if you want other types of styles
html_theme = 'alabaster'

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served. Empty means do not use it
html_use_opensearch = ''

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the documentation:
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory:
# html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation":
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title:
# html_short_title = None

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32 pixels large:
# html_favicon = None

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation:
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format:
# html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities:
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# Let's see by setting to empty if we do not generate html stuff we do not need
# (apparently, it is useless, so comment out):
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to template names:
# html_additional_pages = {}

# If false, no module index is generated:
# html_domain_indices = True

# If false, no index is generated:
# html_use_index = True

# If true, the index is split into individual pages for each letter:
# html_split_index = False

# If true, links to the reST sources are added to the pages:
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True:
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True:
# html_show_copyright = True

# This is the file name suffix for HTML files (e.g. ".xhtml"):
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# (Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'):
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value:
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used:
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder:
# htmlhelp_basename = 'reportbuilddoc'

# -- Options for LaTeX output ---------------------------------------------

# `latex_documents` has been defined above and should NOT be changed

# A list of file names, relative to the configuration directory, to copy to the build directory
# when building LaTeX output. (Note: changed in version 1.2: This overrides the files which is
# provided from Sphinx such as sphinx.sty):
latex_additional_files = [os.path.join('conf_files/latex/additional_files', c)
                          for c in os.listdir("conf_files/latex/additional_files")]

latex_elements = {
    # not toc:
    'tableofcontents': u'',
    # The paper size ('letterpaper' or 'a4paper'):
    'papersize': 'a4paper',
    # The font size ('10pt', '11pt' or '12pt'):
    'pointsize': '12pt',
    # Latex figure (float) alignment
    'figure_align': '!ht',
    'geometry': '\usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}',
    # Sphinx has too fancy stuff: titles as \sfseries\bfseries,
    # and title colors (which applies to ALL section titles) a sort of blue
    # set the former as normal bfseries, and the latter as black
    # (NOTE THAT Title Color applies to ALL section/chapter titles in sphinx 1.5.1):
    'sphinxsetup': "HeaderFamily=\\bfseries,TitleColor={rgb}{0,0,0}",
    # sphinx preamble (http://www.sphinx-doc.org/en/stable/config.html#confval-latex_elements):
    'preamble': r'\makeatletter\input{latex.preamble.tex}\makeatother',
    # latex epilog (http://www.sphinx-doc.org/en/stable/config.html#confval-latex_elements):
    'atendofbody': r'\makeatletter\input{latex.atendofbody.tex}\makeatother',
}

# Short comment: set the next flag to True.
# Long comment: Sphinx defines in its sphinx.sty file (added by default in the latex dir)
# custom styling commands. To avoid conflicts, these commands were redefined from version
# 1.4+ into \sphinx<foo>, e.g. \sphinxtablecontinued instead of \tablecontinued.
# What THEY claim is that, if we want to avoid conflicts, we can set the next parameter to False
# What is TRUE is that, if we want to avoid latex 'undefined control sequence' errors, you better
# keep it to True (basically, sphinx 1.5.2 still issues old macro commands). Note that we do not
# upgrade to newer version of sphinx because currently (1.6+) they have a completely
# new latex templating system still under development. Waiting for that to be stable, we set:
latex_keep_old_macro_names = True

# The name of an image file (relative to this directory) to place at the top of the title page:
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts, not chapters:
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links:
# latex_show_urls = False

# Documents to append as an appendix to all manuals:
# latex_appendices = []

# If false, no module index is generated:
# latex_domain_indices = True

# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# man and texinfo not supported. Uncomment below:
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# # -- Options for manual page output ---------------------------------------
#
# # One entry per manual page. List of tuples
# # (source start file, name, description, authors, manual section).
# man_pages = [
#     (master_doc, project, u'' if not project else project + u' Documentation',
#      [author], 1)
# ]
#
# # If true, show URL addresses after external links.
# #man_show_urls = False
#
#
# # -- Options for Texinfo output -------------------------------------------
#
# # Grouping the document tree into Texinfo files. List of tuples
# # (source start file, target name, title, author,
# #  dir menu entry, description, category)
# texinfo_documents = [
#     (master_doc, project, u'' if not project else project + u' Documentation',
#      author, project, 'One line description of project.',
#      'Miscellaneous'),
# ]

# Documents to append as an appendix to all manuals.
# #texinfo_appendices = []

# If false, no module index is generated.
# #texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# #texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# #texinfo_no_detailmenu = False
